name: Run QA tests (static analysis, lint and unit tests)
on: [pull_request]

jobs:
  run-qa-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        php: ['8.2', '8.4']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none

      - name: Composer install
        run: composer install
      
      - name: Run QA tests
        run: composer check-ci
