name: Run QA tests (static analysis, lint and unit tests)
on: [pull_request]

jobs:
  run-qa-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /var/www/html/
    container:
      image:  ghcr.io/openconext/openconext-basecontainers/php82-apache2-node20-composer2:latest
      volumes:
        - .:/var/www/html

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Composer install
        run: composer install
      
      - name: Run QA tests
        run: composer check
